# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5e3ce2443060f4d4781082d94708c93228e9c0cca24c7a4d141ed215eb1c0065c6a4e39e3a9f597e0ce1d44c0a48eabc8e1e944fdca7353b355651840e2051b

test:
  secret_key_base: 31a9a5f67ae3e8b6c36d13bd15ad5d3d0be3ace6ff862097e16f5e1b3ce3f7ac50e1b5851648cb14442fe580b9af8b5b1d9a8107fe0d4a455364b0637bf693f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
